/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author María José
 */
public class addLibrosGUI extends javax.swing.JFrame {

    /**
     * Creates new form addLibros
     */
    
    Libros l;
    public addLibrosGUI() {
        initComponents();
        txtNombre.setText("");
        txtAutor.setText("");
        txtLugar.setText("");
        txtA.setText("");
        txtEd.setText("");
         txtCat.setText("");
        txtPag.setText("");
        txtNoE.setText("");
       // m.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtEd = new javax.swing.JTextField();
        txtCat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPag = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtNoE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bibliotecaM = new javax.swing.JMenu();
        inicioS = new javax.swing.JMenuItem();
        datosSM = new javax.swing.JMenuItem();
        usuariosM = new javax.swing.JMenu();
        alumnoSM = new javax.swing.JMenu();
        addAlumno = new javax.swing.JMenuItem();
        showListAlumnos = new javax.swing.JMenuItem();
        profesorSM = new javax.swing.JMenu();
        addProfesor = new javax.swing.JMenuItem();
        showListProfesor = new javax.swing.JMenuItem();
        itemsM = new javax.swing.JMenu();
        librosSM = new javax.swing.JMenu();
        addLibro = new javax.swing.JMenuItem();
        showListLibros = new javax.swing.JMenuItem();
        tesisSM = new javax.swing.JMenu();
        addTesis = new javax.swing.JMenuItem();
        showListTesis = new javax.swing.JMenuItem();
        prestamosM = new javax.swing.JMenu();
        realizarPS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel3.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtNombre.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel4.setText("Autor:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel5.setText("Lugar de Publicación:");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel6.setText("Año de Publicación:");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel7.setText("Editorial");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel8.setText("Categoria:  ");

        txtAutor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtAutor.setText("jTextField1");

        txtLugar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtLugar.setText("jTextField1");
        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel1.setText("REGISTRO DE LIBROS");

        txtA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtA.setText("jTextField1");

        txtEd.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtEd.setText("jTextField1");

        txtCat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtCat.setText("jTextField1");
        txtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel9.setText("No. páginas: ");

        txtPag.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtPag.setText("jTextField1");

        btnRegistrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtNoE.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtNoE.setText("jTextField1");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel10.setText("Edición: ");

        bibliotecaM.setText("Biblioteca");

        inicioS.setText("Inicio");
        inicioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioSActionPerformed(evt);
            }
        });
        bibliotecaM.add(inicioS);

        datosSM.setText("Modificar Datos Bibliotca");
        datosSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosSMActionPerformed(evt);
            }
        });
        bibliotecaM.add(datosSM);

        jMenuBar1.add(bibliotecaM);

        usuariosM.setText("Usuarios");

        alumnoSM.setText("Alumno");

        addAlumno.setText("Registrar");
        addAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlumnoActionPerformed(evt);
            }
        });
        alumnoSM.add(addAlumno);

        showListAlumnos.setText("Elimiar");
        showListAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListAlumnosActionPerformed(evt);
            }
        });
        alumnoSM.add(showListAlumnos);

        usuariosM.add(alumnoSM);

        profesorSM.setText("Profesor");

        addProfesor.setText("Registrar");
        addProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfesorActionPerformed(evt);
            }
        });
        profesorSM.add(addProfesor);

        showListProfesor.setText("Elimiar");
        showListProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListProfesorActionPerformed(evt);
            }
        });
        profesorSM.add(showListProfesor);

        usuariosM.add(profesorSM);

        jMenuBar1.add(usuariosM);

        itemsM.setText("Items");

        librosSM.setText("Libros");

        addLibro.setText("Registrar");
        addLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibroActionPerformed(evt);
            }
        });
        librosSM.add(addLibro);

        showListLibros.setText("Eliminar");
        showListLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListLibrosActionPerformed(evt);
            }
        });
        librosSM.add(showListLibros);

        itemsM.add(librosSM);

        tesisSM.setText("Tesis");

        addTesis.setText("Registrar");
        addTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTesisActionPerformed(evt);
            }
        });
        tesisSM.add(addTesis);

        showListTesis.setText("Eliminar");
        showListTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListTesisActionPerformed(evt);
            }
        });
        tesisSM.add(showListTesis);

        itemsM.add(tesisSM);

        jMenuBar1.add(itemsM);

        prestamosM.setText("Prestamos");

        realizarPS.setText("Realizar");
        realizarPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPSActionPerformed(evt);
            }
        });
        prestamosM.add(realizarPS);

        jMenuBar1.add(prestamosM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(txtAutor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txtLugar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel10)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoE, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEd, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                        .addComponent(txtPag, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnRegistrar)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addComponent(txtCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarActionPerformed

    private void txtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        String no, au, lu, a, ed, cat, pag, noe;
        no=txtNombre.getText();
        au=txtAutor.getText();
        lu=txtLugar.getText();
        a=txtA.getText();
        ed=txtEd.getText();
         cat=txtCat.getText();
        pag=txtPag.getText();
        noe=txtNoE.getText();
        
     //    Libros(String  id, String au, String nom, String lu, String an, String nte, String edi,String c, String ne,String pag)
        
        l= new Libros("", au, no, lu,  a,  ed, cat, noe,pag);
        l.Agregar();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void inicioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioSActionPerformed
        // Biblioteca
        BibliotecaGUI bb = new BibliotecaGUI();
        bb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inicioSActionPerformed

    private void datosSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosSMActionPerformed
        // MANDA A LA VENTANA PARA  CAMBIAR LOS DATOS

        DatosBibliotecaGUI b1 = new DatosBibliotecaGUI();
        b1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datosSMActionPerformed

    private void addAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlumnoActionPerformed
        // TODO add your handling code here:

        addAlumnosGUI sp = new addAlumnosGUI();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAlumnoActionPerformed

    private void showListAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListAlumnosActionPerformed
        // TODO add your handling code here:
        eliminarAlumnoGUI sl = new eliminarAlumnoGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListAlumnosActionPerformed

    private void addProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfesorActionPerformed
        // TODO add your handling code here:
        addProfesorGUI sl = new addProfesorGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addProfesorActionPerformed

    private void showListProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListProfesorActionPerformed
        // TODO add your handling code here:
        eliminarProfesorGUI sp = new eliminarProfesorGUI();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListProfesorActionPerformed

    private void addLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibroActionPerformed
        // TODO add your handling code here:
        addLibrosGUI sl = new addLibrosGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addLibroActionPerformed

    private void showListLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListLibrosActionPerformed
        // TODO add your handling code here:

        eliminarLibroGUI sl = new eliminarLibroGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListLibrosActionPerformed

    private void addTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTesisActionPerformed
        // TODO add your handling code here:
        addTesisGUI t1= new addTesisGUI();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addTesisActionPerformed

    private void showListTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListTesisActionPerformed
        // TODO add your handling code here:
        eliminarTesisGUI sl = new eliminarTesisGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListTesisActionPerformed

    private void realizarPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPSActionPerformed
        // TODO add your handling code here:
        addPrestamoGUI t1= new addPrestamoGUI();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_realizarPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addLibrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addLibrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addLibrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addLibrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addLibrosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAlumno;
    private javax.swing.JMenuItem addLibro;
    private javax.swing.JMenuItem addProfesor;
    private javax.swing.JMenuItem addTesis;
    private javax.swing.JMenu alumnoSM;
    private javax.swing.JMenu bibliotecaM;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JMenuItem datosSM;
    private javax.swing.JMenuItem inicioS;
    private javax.swing.JMenu itemsM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu librosSM;
    private javax.swing.JMenu prestamosM;
    private javax.swing.JMenu profesorSM;
    private javax.swing.JMenuItem realizarPS;
    private javax.swing.JMenuItem showListAlumnos;
    private javax.swing.JMenuItem showListLibros;
    private javax.swing.JMenuItem showListProfesor;
    private javax.swing.JMenuItem showListTesis;
    private javax.swing.JMenu tesisSM;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtEd;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNoE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPag;
    private javax.swing.JMenu usuariosM;
    // End of variables declaration//GEN-END:variables
}
