/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author María José
 */
public class BibliotecaGUI extends javax.swing.JFrame {

    /**
     * Creates new form BibliotecGUI
     */
    public BibliotecaGUI() {
        initComponents();
        lbl1.setText("xD");
          lbl3.setText("Cesar");
            lbl2.setText("UPIIZ");
              lbl4.setText("sin numero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bibliotecaM = new javax.swing.JMenu();
        inicioS = new javax.swing.JMenuItem();
        datosSM = new javax.swing.JMenuItem();
        usuariosM = new javax.swing.JMenu();
        alumnoSM = new javax.swing.JMenu();
        addAlumno = new javax.swing.JMenuItem();
        showListAlumnos = new javax.swing.JMenuItem();
        profesorSM = new javax.swing.JMenu();
        addProfesor = new javax.swing.JMenuItem();
        showListProfesor = new javax.swing.JMenuItem();
        itemsM = new javax.swing.JMenu();
        librosSM = new javax.swing.JMenu();
        addLibro = new javax.swing.JMenuItem();
        showListLibros = new javax.swing.JMenuItem();
        tesisSM = new javax.swing.JMenu();
        addTesis = new javax.swing.JMenuItem();
        showListTesis = new javax.swing.JMenuItem();
        prestamosM = new javax.swing.JMenu();
        realizarPS = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem7.setText("jMenuItem7");
        jPopupMenu1.add(jMenuItem7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        jLabel2.setText("Nombre :");

        jLabel3.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        jLabel3.setText("Encargado : ");

        jLabel4.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        jLabel4.setText("Dirección :");

        jLabel5.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        jLabel5.setText("Telefono :");

        lbl3.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        lbl3.setForeground(new java.awt.Color(9, 13, 0));
        lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl4.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        lbl4.setForeground(new java.awt.Color(9, 13, 0));
        lbl4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl1.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        lbl1.setForeground(new java.awt.Color(9, 13, 0));
        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl2.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        lbl2.setForeground(new java.awt.Color(9, 13, 0));
        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bibliotecaM.setText("Biblioteca");

        inicioS.setText("Inicio");
        inicioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioSActionPerformed(evt);
            }
        });
        bibliotecaM.add(inicioS);

        datosSM.setText("Modificar Datos Bibliotca");
        datosSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosSMActionPerformed(evt);
            }
        });
        bibliotecaM.add(datosSM);

        jMenuBar1.add(bibliotecaM);

        usuariosM.setText("Usuarios");

        alumnoSM.setText("Alumno");

        addAlumno.setText("Registrar");
        addAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlumnoActionPerformed(evt);
            }
        });
        alumnoSM.add(addAlumno);

        showListAlumnos.setText("Elimiar");
        showListAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListAlumnosActionPerformed(evt);
            }
        });
        alumnoSM.add(showListAlumnos);

        usuariosM.add(alumnoSM);

        profesorSM.setText("Profesor");

        addProfesor.setText("Registrar");
        addProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfesorActionPerformed(evt);
            }
        });
        profesorSM.add(addProfesor);

        showListProfesor.setText("Elimiar");
        showListProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListProfesorActionPerformed(evt);
            }
        });
        profesorSM.add(showListProfesor);

        usuariosM.add(profesorSM);

        jMenuBar1.add(usuariosM);

        itemsM.setText("Items");

        librosSM.setText("Libros");

        addLibro.setText("Registrar");
        addLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibroActionPerformed(evt);
            }
        });
        librosSM.add(addLibro);

        showListLibros.setText("Eliminar");
        showListLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListLibrosActionPerformed(evt);
            }
        });
        librosSM.add(showListLibros);

        itemsM.add(librosSM);

        tesisSM.setText("Tesis");

        addTesis.setText("Registrar");
        addTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTesisActionPerformed(evt);
            }
        });
        tesisSM.add(addTesis);

        showListTesis.setText("Eliminar");
        showListTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListTesisActionPerformed(evt);
            }
        });
        tesisSM.add(showListTesis);

        itemsM.add(tesisSM);

        jMenuBar1.add(itemsM);

        prestamosM.setText("Prestamos");

        realizarPS.setText("Realizar");
        realizarPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPSActionPerformed(evt);
            }
        });
        prestamosM.add(realizarPS);

        jMenuBar1.add(prestamosM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(64, 64, 64)
                                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4))
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioSActionPerformed
        // Biblioteca
        BibliotecaGUI bb = new BibliotecaGUI();
        bb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inicioSActionPerformed

    private void datosSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosSMActionPerformed
        // MANDA A LA VENTANA PARA  CAMBIAR LOS DATOS

        DatosBibliotecaGUI b1 = new DatosBibliotecaGUI();
        b1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datosSMActionPerformed

    private void addAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlumnoActionPerformed
        // TODO add your handling code here:

        addAlumnosGUI sp = new addAlumnosGUI();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAlumnoActionPerformed

    private void showListAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListAlumnosActionPerformed
        // TODO add your handling code here:
        eliminarAlumnoGUI sl = new eliminarAlumnoGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListAlumnosActionPerformed

    private void addProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfesorActionPerformed
        // TODO add your handling code here:
        addProfesorGUI sl = new addProfesorGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addProfesorActionPerformed

    private void showListProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListProfesorActionPerformed
        // TODO add your handling code here:
        eliminarProfesorGUI sp = new eliminarProfesorGUI();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListProfesorActionPerformed

    private void addLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibroActionPerformed
        // TODO add your handling code here:
        addLibrosGUI sl = new addLibrosGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addLibroActionPerformed

    private void showListLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListLibrosActionPerformed
        // TODO add your handling code here:

        eliminarLibroGUI sl = new eliminarLibroGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListLibrosActionPerformed

    private void addTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTesisActionPerformed
        // TODO add your handling code here:
        addTesisGUI t1= new addTesisGUI();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addTesisActionPerformed

    private void showListTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListTesisActionPerformed
        // TODO add your handling code here:
        eliminarTesisGUI sl = new eliminarTesisGUI();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showListTesisActionPerformed

    private void realizarPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPSActionPerformed
        // TODO add your handling code here:
        addPrestamoGUI t1= new addPrestamoGUI();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_realizarPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAlumno;
    private javax.swing.JMenuItem addLibro;
    private javax.swing.JMenuItem addProfesor;
    private javax.swing.JMenuItem addTesis;
    private javax.swing.JMenu alumnoSM;
    private javax.swing.JMenu bibliotecaM;
    private javax.swing.JMenuItem datosSM;
    private javax.swing.JMenuItem inicioS;
    private javax.swing.JMenu itemsM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JMenu librosSM;
    private javax.swing.JMenu prestamosM;
    private javax.swing.JMenu profesorSM;
    private javax.swing.JMenuItem realizarPS;
    private javax.swing.JMenuItem showListAlumnos;
    private javax.swing.JMenuItem showListLibros;
    private javax.swing.JMenuItem showListProfesor;
    private javax.swing.JMenuItem showListTesis;
    private javax.swing.JMenu tesisSM;
    private javax.swing.JMenu usuariosM;
    // End of variables declaration//GEN-END:variables
}
